server:
  port: 8081
spring:
  redis:
    host: 192.168.1.6
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 100s
      shutdown-timeout: 1000
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
mybatis-plus:
  type-aliases-package: "com.org.entity"
  global-config:
    db-config:
      table-prefix: tb_
logging:
  level:
    com.org: debug
  pattern:
    dateformat: MM-dd HH:mm:ss
  file:
    path: D:\log
    max-history: 2
    max-size: 1024KB
    clean-history-on-start: true